### ISSUE TITLE
SPARK available through NOMISnet

### ISSUE THREAD

**Issue by rgarciasantos** [earthblink/nomis-foundation#5]
Dear collagues,

I was wondering whether you have any updates on seeing the feasibility of making available the SPARK magazine online (ONLY though the NOMIS app and web version) while not allowing its download or printing.
Many thanks for the feedback
RUben

**Comment by earthblink** [comment]
Dear Ruben,

There are several issues with this idea.

First of all, the current design of spark has very small type in order to be read on a mobile phone, tablet or on a 13 inch laptop. The users would only be able to read the magazine if they have a 15 inch monitor or larger. It would therefore only be available to such users.

We have researched the possibility to program a magazine flipping code, but such programming would not be recommended by us due to slowing down the operation of the app and bugs.

Furthermore, the idea of not being able to print or download the PDF file is counterintuitive based on the fact that we are offering this service to an elite group of 31 scientists, that would probably wish to maybe print print a few pages to share with others or maybe read during a flight. Again adding such features as restricting downloading and printing are problematic coding practices.
